### ISSUE TITLE
Team Meeting - Tuesday October 1st, 2024

### ISSUE THREAD

**Issue by arvindshastri** [nguyes44/MacTransit#27]
**Date and Time**
Tuesday October 1st, 2024 - 7:15pm to 8:50pm

**Attendance**

- [x] Aysu Ozdal
- [x] Andrew Thompson
- [x] Arvind Shastri
- [x] George Yazji
- [x] Stanley Nguyen

**Agenda**

- Talk about potential GPS solutions
- Talk about survey questions for data elicitation

**Meeting Notes**

- Install GPS related software on a recent Android version device so that there are no foreseeable integration issues
- The bus driver interface is built on top of the GPS specific application and provides all necessary functions for the driver such as counting number of people, reporting bus statuses or issues.

- App can get GPS data of other buses on the map. Bus driver can quickly see where other buses are.
- Notifs can be sent to bus drivers to let them know where they are relative to other buses (10 mins ahead, etc.)

Q: Do we really need the driver to be responsible where other buses are around them? 
- PO admin should be responsible for spacing out.
- maccio mentioned there are many different ways to manage traffic and buses spacing out.
- bus drivers cannot do anything after the buses are dispatched. cannot make commuters wait on the bus.

- Location data should only be directed to PO. PO should try to dispatch buses once a bus reaches the far end of the route to initially try spacing them out. they can make an informed decision.
- app "suggests" dispatching time to the PO admin.

- sending notifications back to the bus driver isn't an implementation issue, but a cost issue.
- syncing process and connecting to firebase notifications is an unfamiliar implementation.
- there is a data usage cost vs firebase cost.

- Bus' capacity can be demonstrated to the user on a scale from [Not busy / Slightly busy /  Very busy]
- Driver can also flag a bus as "Not Taking" for a multitude of reasons (e.g. bus is full, bus is broken, etc.)
- Capacity scale can be derived from statistics that bus driver inputs at every stop when counting commuters coming on/off
- Abstracts the capacity from quantitative numbers to a qualitative scale, since bus driver counting is prone to human error

Potential survey questions:
1. How often do you take the shuttle bus?
2. On average, how large is your wait time for a shuttle bus?
3. How often do you miss the shuttle bus you expected to take? By how much time? 
4. How frustrated are you when you miss your shuttle bus, or wait a long time to hop on the next one?
5. On average, how much do you have to wait for the NEXT shuttle bus if you missed the current one?
6. If you were able to see where shuttle buses were on campus, would you consider waiting for them? And for how long?
7. What information would you want to see related to shuttle bus transportation on and off campus?
8. In an app that could provide live tracking for shuttle buses on/off campus, what information would you find the most important to see?
9. If you were to create your own transit app for shuttle buses on/off campus, what are some things that you might include that would improve your commuting experience?
10. How difficult was/is it to learn where the shuttle bus stops are on a given route?
11. Would you plan your commute to campus around shuttle bus arrival times, if possible?
12. If applicable, tell us (in detail) about a negative shuttle bus experience.
13. If you would like to be involved in an interview / testing session, please provide us an email with which we can contact you at a later date. 
14. Would seeing the capacity of a bus make you feel more/less inclined to waiting for it?

**Action Items**
- Sort questions in an approachable manner (and potentially add MCQ answers)
- Ask around for a lamination process (to avoid bad weather outside)
- Generate a QR code compatible survey based on these results
- Post this survey to the McMaster subreddit
- Print and post this QR code with a tagline (around 10) at shuttle bus stops (upon Dean's approval)

**Comment by nguyes44** [comment]
takeaways / action items transferred to other issues
